[package]
name = "iobc-supervisor-service"
version = "0.1.0"
authors = ["Ryan Plauche <ryan@kubos.co>"]

[dependencies]
juniper =  "0.9.2"
isis-iobc-supervisor = { path = "../../apis/isis-iobc-supervisor" }
kubos-service = { path = "../kubos-service" }
