[[communication-service]]
name = "Local UDP Services"
transport = "udp"

# [[communication-service]]
# name = "Beaglebone Internal Serial"
# transport = "serial"
# device = "/dev/ttyO4"
# baud = 115200

[[communication-service]]
name = "Beaglebone Debug Serial"
transport = "debug-serial"
baud = 115200
